import type { Config } from "tailwindcss";

const hubblePreset: Partial<Config> = {
  darkMode: ["class"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Roboto", "sans-serif"],
        mono: ["Roboto Mono", "monospace"],
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
          bg: "var(--primary-bg)",
          accent: "var(--primary-accent)",
          "accent-2": "var(--primary-accent-2)",
          50: "#ebfbff",
          100: "#d1f4ff",
          200: "#a8eeff",
          300: "#70e7ff",
          400: "#2ed5ff",
          500: "#00b3fa",
          600: "#008ae0",
          700: "#0071db",
          800: "#0057a8",
          900: "#064374",
          950: "#051d33",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
          50: "#fafafa",
          100: "#f4f4f5",
          200: "#e4e4e7",
          300: "#d4d4d8",
          400: "#a1a1aa",
          500: "#71717a",
          600: "#52525b",
          700: "#3f3f46",
          800: "#27272a",
          900: "#18181b",
          950: "#09090b",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
          bg: "var(--destructive-bg)",
          subtle: "var(--destructive-subtle)",
          accent: "var(--destructive-accent)",
          50: "#fef2f2",
          100: "#ffe2e2",
          200: "#fecaca",
          300: "#fca5a5",
          400: "#f87171",
          500: "#ef4444",
          600: "#dc2626",
          700: "#b91c1c",
          800: "#991b1b",
          900: "#7f1d1d",
          950: "#450a0a",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
          0: "var(--accent-0)",
          2: "var(--accent-2)",
          3: "var(--accent-3)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
          border: "var(--card-border)",
        },
        tooltip: {
          DEFAULT: "var(--tooltip)",
          foreground: "var(--tooltip-foreground)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          accent: "var(--sidebar-accent)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
          muted: "var(--sidebar-muted)",
        },
        hover: {
          primary: "var(--hover-primary)",
          secondary: "var(--hover-secondary)",
          destructive: "var(--hover-destructive)",
          ghost: "var(--hover-ghost)",
          outline: "var(--hover-outline)",
        },
        disabled: {
          DEFAULT: "var(--disabled)",
          foreground: "var(--disabled-foreground)",
        },
        border: {
          DEFAULT: "var(--border)",
          50: "var(--border-50)",
          100: "var(--border-100)",
          200: "var(--border-200)",
          300: "var(--border-300)",
          destructive: "var(--border-destructive)",
          primary: "var(--border-primary)",
        },
        input: {
          DEFAULT: "var(--input)",
          bg: "var(--input-bg)",
          disabled: "var(--input-disabled)",
        },
        ring: "var(--ring)",
        ghost: "var(--ghost)",
        "outline-bg": "var(--outline-bg)",
        "outline-active": "var(--outline-active)",
        success: {
          DEFAULT: "var(--success-text)",
          bg: "var(--success-bg)",
          50: "#f0fdf4",
          100: "#dcfce7",
          200: "#bbf7d0",
          300: "#86efac",
          400: "#4ade80",
          500: "#22c55e",
          600: "#16a34a",
          700: "#15803d",
          800: "#166534",
          900: "#14532d",
          950: "#052e16",
        },
        warning: {
          DEFAULT: "var(--warning-text)",
          bg: "var(--warning-bg)",
          50: "#fffbeb",
          100: "#fef3c7",
          200: "#fde68a",
          300: "#fcd34d",
          400: "#fbbf24",
          500: "#f59e0b",
          600: "#d97706",
          700: "#b45309",
          800: "#92400e",
          900: "#78350f",
          950: "#451a03",
        },
      },
      borderRadius: {
        none: "0",
        xs: "2px",
        sm: "4px",
        DEFAULT: "8px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "2xl": "24px",
        full: "9999px",
      },
      fontSize: {
        "caption-sm": ["10px", { lineHeight: "16px", letterSpacing: "0" }],
        caption: ["12px", { lineHeight: "18px", letterSpacing: "0" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0" }],
        body: ["16px", { lineHeight: "24px", letterSpacing: "0" }],
        "heading-5": ["20px", { lineHeight: "24px", letterSpacing: "0" }],
        "heading-4": ["24px", { lineHeight: "28px", letterSpacing: "-0.01em" }],
        "heading-3": ["32px", { lineHeight: "32px", letterSpacing: "-0.01em" }],
        "heading-2": ["40px", { lineHeight: "40px", letterSpacing: "-0.01em" }],
        "heading-1": ["56px", { lineHeight: "56px", letterSpacing: "-0.015em" }],
      },
      boxShadow: {
        "2xs": "0 1px 0 0 rgba(0,0,0,0.05)",
        xs: "0 1px 2px 0 rgba(0,0,0,0.05)",
        sm: "0 1px 2px -1px rgba(0,0,0,0.10), 0 1px 3px 0 rgba(0,0,0,0.10)",
        DEFAULT: "0 2px 4px -2px rgba(0,0,0,0.10), 0 4px 6px -1px rgba(0,0,0,0.10)",
        md: "0 2px 4px -2px rgba(0,0,0,0.10), 0 4px 6px -1px rgba(0,0,0,0.10)",
        lg: "0 4px 6px -4px rgba(0,0,0,0.10), 0 10px 15px -3px rgba(0,0,0,0.10)",
        xl: "0 8px 10px -6px rgba(0,0,0,0.10), 0 20px 25px -5px rgba(0,0,0,0.10)",
        "2xl": "0 25px 50px -12px rgba(0,0,0,0.10)",
        "focus-ring": "0 0 0 3px var(--ring)",
        "focus-ring-error": "0 0 0 3px var(--ring-error)",
        none: "none",
      },
      backdropBlur: {
        light: "4px",
        full: "12px",
      },
      keyframes: {
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        shimmer: "shimmer 2.5s ease-in-out infinite",
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
};

export default hubblePreset;
